In [2]:
import pandas as pd

In [9]:
usa = pd.read_csv("usa_21.txt", sep='\t', encoding='latin1')

In [10]:
usa

,name,age,info,address,address_content,historical_address,phones,phones_content,emails,emails_content,tags,description
0,Matthew T Filippini,50,He is in his forties. The age of Matthew is fi...,US;60093;Winnetka;IL;Cook County;1703180030010...,"1148 Oakley Ave, Winnetka, IL 60093 Single Fam...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,", Floor Size - 5,440 sqft Parcel ID# 051711808...",NaN,â¢ (847) 441-7407 â¢ (815) 441-7407,"(847) 441-7407, (815) 441-7407 Possible connec...",NaN,NaN,â¢ IL â¢ Winnetka IL â¢ 50-60 â¢ 847 â¢ 815,â¢ Possible connections via main address â¢ ...,NaN,NaN,NaN,NaN
2,Matthew Filippini,57,He is in his fifties. The current age of Matth...,US;60645;Chgo;IL;Cook County;170310203023006;;...,"2418 W Greenleaf Ave, Chicago, IL 60645 County...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"ude: 42.0098709, -87.690465",NaN,â¢ (312) 952-0401 â¢ (773) 882-7733,"(312) 952-0401, (773) 882-7733 Possible connec...",â¢ matthew.filippini@cs.com,matthew.filippini@cs.com Possible connections ...,â¢ IL â¢ Chgo IL â¢ 50-60 â¢ 312 â¢ 773,â¢ Possible connections via main address â¢ ...,NaN,NaN,NaN,NaN
4,Matthew A Filippini,NaN,The residency of Matthew is at 1426 Park Shore...,US;33901;Fort Myers;FL;Lee County;120710010001...,"1426 Park Shore Cir, Fort Myers, FL 33901 Coun...",NaN,â¢ (239) 931-4099,(239) 931-4099 Possible connections via phone ...,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
998845,Nicola Yvonne Felton,56,06.01.67 is her birth date. Nicola is a fifty-...,US;48228;Detroit;MI;Wayne County;2616354560030...,"6773 Asbury Park, Detroit, MI 48228 Single Fam...",NaN,NaN,NaN,NaN,NaN,â,NaN
998846,¢ MI â¢ Detroit MI â¢ 50-60,â¢ Possible connections via main address â¢ ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998847,Nicola H Felton,68,The listed education level was a professional ...,US;27938;Gatesville;NC;Gates County;3707397010...,"176 Perkins Rd, Gatesville, NC 27938 County: G...",NaN,â¢ (252) 357-1941,(252) 357-1941 Possible connections via phone ...,NaN,NaN,NaN,NaN
998848,NaN,NaN,â¢ NC â¢ Gatesville NC â¢ 60-100 â¢ 252,â¢ Possible connections via main address;;â¢...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998849,Olga Felton,63,Nurse (Registered) is an occupation. Olga was ...,US;46385;Valparaiso;IN;Porter County;181270507...,"470 Grove Ave, Valparaiso, IN 46385 Single Fam...",NaN,NaN,NaN,NaN,NaN,NaN,NaN